### ISSUE TITLE
Conflict with AlchemistNPC lite v1.8.16 mod 

### ISSUE THREAD

**Issue by blacqvve** [Apacchii/ApacchiisClassesMod2#2]
I will leave the exceptions here, hope you can push a fix or you can guide me to how to edit mod codes.

`Terraria.ModLoader.Exceptions.MultipleException: Multiple errors occured.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Item.CountsAsClass(DamageClass damageClass) in tModLoader\Terraria\Item.TML.cs:line 117
   at CalamityMod.ILEditing.ILChanges.LetRogueItemsBeReforgeable(orig_Prefix orig, Item self, Int32 pre) in CalamityMod\ILEditing\VanillaBugfixingILChanges.cs:line 141
   at Terraria.Item.NewItem(IEntitySource source, Int32 X, Int32 Y, Int32 Width, Int32 Height, Int32 Type, Int32 Stack, Boolean noBroadcast, Int32 pfix, Boolean noGrabDelay, Boolean reverseLookup) in tModLoader\Terraria\Item.cs:line 46533
   at Terraria.Player.QuickSpawnItem(IEntitySource source, Int32 item, Int32 stack) in tModLoader\Terraria\Player.cs:line 4141
   at ApacchiisClassesMod2.Items.Classes.BloodMage.OnCreate(ItemCreationContext context) in ApacchiisClassesMod2\Items\Classes\BloodMage.cs:line 58
   at Terraria.ModLoader.ModItem.Register() in tModLoader\Terraria\ModLoader\ModItem.cs:line 84
   at Terraria.ModLoader.ModType.Terraria.ModLoader.ILoadable.Load(Mod mod) in tModLoader\Terraria\ModLoader\ModType.cs:line 34
   at Terraria.ModLoader.Mod.AddContent(ILoadable instance) in tModLoader\Terraria\ModLoader\Mod.cs:line 132
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 49
   --- End of inner exception stack trace ---
   at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 60
   at Terraria.ModLoader.Mod.Autoload() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 63
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 314
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 371
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 304`

**Comment by blacqvve** [comment]
[log.txt](https://github.com/Apacchii/ApacchiisClassesMod2/files/9329111/log.txt)
